#!/usr/bin/env python3
"""
WAF 指纹识别工具
通过发送特定恶意 payload 触发 WAF 响应，结合内置 WAF 指纹数据库（15+ 种 WAF）
分析响应状态码、响应头和响应体，识别目标网站使用的 WAF 类型。
"""

import argparse
import json
import os
import sys
import time

try:
    import requests
    import urllib3
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
except ImportError:
    requests = None


# ============================================================
# WAF 指纹数据库（15+ 种 WAF）
# 每个条目包含：WAF 名称、检测特征（响应头、响应体关键词、状态码）
# ============================================================

WAF_FINGERPRINTS = [
    {
        "name": "Cloudflare",
        "headers": {
            "server": ["cloudflare"],
            "cf-ray": [""],  # 存在即匹配
            "cf-cache-status": [""],
        },
        "body_patterns": ["cloudflare", "cf-ray", "__cf_bm__", "attention required", "cf-chl-bypass"],
        "block_status": [403, 503],
        "confidence": "high",
    },
    {
        "name": "AWS WAF",
        "headers": {
            "x-amzn-trace-id": [""],
            "x-amz-cf-id": [""],
        },
        "body_patterns": ["request blocked", "aws waf", "amazonaws"],
        "block_status": [403],
        "confidence": "high",
    },
    {
        "name": "Akamai",
        "headers": {
            "server": ["akamaighost", "akamai"],
            "x-akamai-transformed": [""],
        },
        "body_patterns": ["akamai", "access denied", "reference #"],
        "block_status": [403, 429],
        "confidence": "high",
    },
    {
        "name": "ModSecurity",
        "headers": {
            "server": ["mod_security", "modsecurity"],
        },
        "body_patterns": ["mod_security", "modsecurity", "not acceptable", "mod-security"],
        "block_status": [403, 406],
        "confidence": "high",
    },
    {
        "name": "F5 BIG-IP",
        "headers": {
            "server": ["bigip"],
            "x-cnection": [""],
            "bigipserver": [""],
        },
        "body_patterns": ["bigip", "f5 networks", "the requested url was rejected"],
        "block_status": [403, 501],
        "confidence": "high",
    },
    {
        "name": "Imperva Incapsula",
        "headers": {
            "x-iinfo": [""],
            "x-cdn": ["incapsula"],
            "server": ["incapsula"],
        },
        "body_patterns": ["incapsula", "incident id", "help us protect your website"],
        "block_status": [403, 406],
        "confidence": "high",
    },
    {
        "name": "Sucuri",
        "headers": {
            "x-sucuri-id": [""],
            "server": ["sucuri"],
            "x-sucuri-cache": [""],
        },
        "body_patterns": ["sucuri", "access denied - sucuri"],
        "block_status": [403],
        "confidence": "high",
    },
    {
        "name": "Wordfence",
        "headers": {},
        "body_patterns": ["wordfence", "generated by wordfence"],
        "block_status": [403],
        "confidence": "medium",
    },
    {
        "name": "Barracuda",
        "headers": {
            "barra_counter_session": [""],
            "server": ["barracuda"],
        },
        "body_patterns": ["barracuda", "barra_counter"],
        "block_status": [403],
        "confidence": "high",
    },
    {
        "name": "Fortinet FortiWeb",
        "headers": {
            "fortiwafsid": [""],
            "server": ["fortiweb"],
        },
        "body_patterns": ["fortiweb", "fortinet", ".fortiwafsid"],
        "block_status": [403],
        "confidence": "high",
    },
    {
        "name": "Radware",
        "headers": {
            "x-sl-expire": [""],
            "server": ["radware"],
        },
        "body_patterns": ["radware", "cloudflare", "access denied"],
        "block_status": [403],
        "confidence": "medium",
    },
    {
        "name": "Tencent Cloud WAF",
        "headers": {},
        "body_patterns": ["tencent", "腾讯云", "waf.tencent"],
        "block_status": [403, 429],
        "confidence": "medium",
    },
    {
        "name": "Aliyun WAF",
        "headers": {
            "server": ["tengine"],
        },
        "body_patterns": ["aliyun", "阿里云", "error 405", "request rejected"],
        "block_status": [405, 403],
        "confidence": "medium",
    },
    {
        "name": "Baidu Cloud WAF",
        "headers": {
            "server": ["yunjiasu"],
        },
        "body_patterns": ["baidu", "百度云", "yunjiasu"],
        "block_status": [403],
        "confidence": "medium",
    },
    {
        "name": "dotDefender",
        "headers": {
            "x-dotdefender": [""],
        },
        "body_patterns": ["dotdefender", "dot defender"],
        "block_status": [403],
        "confidence": "high",
    },
    {
        "name": "Citrix Netscaler",
        "headers": {
            "via": ["netscaler"],
        },
        "body_patterns": ["netscaler", "citrix"],
        "block_status": [403],
        "confidence": "medium",
    },
    {
        "name": "IBM Web Application Firewall",
        "headers": {
            "server": ["ibm"],
        },
        "body_patterns": ["ibm", "datapower"],
        "block_status": [403],
        "confidence": "medium",
    },
]


# ============================================================
# 恶意 Payload（用于触发 WAF）
# ============================================================

WAF_TEST_PAYLOADS = [
    {"name": "sql_injection", "payload": "' OR '1'='1", "type": "query"},
    {"name": "xss", "payload": "<script>alert(1)</script>", "type": "query"},
    {"name": "path_traversal", "payload": "../../../etc/passwd", "type": "query"},
    {"name": "command_injection", "payload": ";id", "type": "query"},
    {"name": "large_body", "payload": "A" * 10000, "type": "body"},
]


# ============================================================
# HTTP 请求辅助函数
# ============================================================

def make_request(url, params=None, data=None, timeout=10):
    """发送 HTTP GET/POST 请求。"""
    if requests is None:
        print(json.dumps({"error": "缺少 requests 库，请运行: pip install requests"}), file=sys.stderr)
        sys.exit(1)

    try:
        if data:
            resp = requests.post(url, data=data, timeout=timeout, verify=False, allow_redirects=False)
        else:
            resp = requests.get(url, params=params, timeout=timeout, verify=False, allow_redirects=False)
        return resp
    except requests.exceptions.Timeout:
        return None
    except requests.exceptions.ConnectionError:
        return None
    except Exception:
        return None


# ============================================================
# WAF 检测函数
# ============================================================

def detect_waf(url, timeout):
    """
    检测目标 URL 是否使用 WAF。
    发送恶意 payload 并分析响应，匹配 WAF 指纹数据库。
    """
    # 首先发送正常请求获取基线
    baseline_resp = make_request(url, timeout=timeout)

    # 发送恶意 payload
    blocked_payloads = []
    allowed_payloads = []
    all_responses = []

    for test in WAF_TEST_PAYLOADS:
        if test["type"] == "query":
            resp = make_request(url, params={"q": test["payload"]}, timeout=timeout)
        else:
            resp = make_request(url, data={"input": test["payload"]}, timeout=timeout)

        all_responses.append({
            "payload_name": test["name"],
            "payload": test["payload"][:100],
            "status_code": resp.status_code if resp else None,
            "headers": dict(resp.headers) if resp else {},
            "body_snippet": resp.text[:500] if resp and resp.text else "",
        })

        # 判断是否被阻断
        if resp and resp.status_code in (403, 406, 429, 501, 503):
            blocked_payloads.append(test["name"])
        else:
            allowed_payloads.append(test["name"])

    # 分析所有响应，匹配 WAF 指纹
    detected_wafs = []

    for waf in WAF_FINGERPRINTS:
        match_score = 0
        evidence = []

        for resp_info in all_responses:
            headers = resp_info["headers"]
            body = resp_info["body_snippet"].lower()
            status = resp_info["status_code"]

            # 检查响应头匹配
            for header_name, header_values in waf.get("headers", {}).items():
                for key, value in headers.items():
                    if key.lower() == header_name.lower():
                        if not header_values or any(v.lower() in value.lower() for v in header_values if v):
                            match_score += 2
                            evidence.append(f"响应头匹配: {key}: {value}")

            # 检查响应体匹配
            for pattern in waf.get("body_patterns", []):
                if pattern.lower() in body:
                    match_score += 2
                    evidence.append(f"响应体匹配: '{pattern}'")

            # 检查状态码匹配
            if status and status in waf.get("block_status", []):
                match_score += 1
                evidence.append(f"阻断状态码: {status}")

        if match_score >= 2:
            detected_wafs.append({
                "name": waf["name"],
                "confidence": waf["confidence"] if match_score >= 3 else "low",
                "score": match_score,
                "evidence": evidence[:5],  # 限制证据数量
            })

    # 确定最终结果
    waf_detected = len(detected_wafs) > 0 or len(blocked_payloads) > 0

    if detected_wafs:
        # 取分数最高的
        detected_wafs.sort(key=lambda x: x["score"], reverse=True)
        best_match = detected_wafs[0]
        waf_name = best_match["name"]
        confidence = best_match["confidence"]
        evidence = best_match["evidence"]
    else:
        waf_name = "Unknown" if waf_detected else "None"
        confidence = "low" if waf_detected else "high"
        if waf_detected:
            evidence = [f"检测到 {len(blocked_payloads)} 个 payload 被阻断，但无法确定 WAF 类型"]
        else:
            evidence = ["未检测到 WAF"]

    # 判断绕过难度
    bypass_difficulty = "easy"
    if waf_detected:
        if len(blocked_payloads) >= 4:
            bypass_difficulty = "hard"
        elif len(blocked_payloads) >= 2:
            bypass_difficulty = "medium"
        else:
            bypass_difficulty = "easy"

    return {
        "url": url,
        "waf_detected": waf_detected,
        "waf_name": waf_name,
        "confidence": confidence,
        "evidence": evidence,
        "block_behavior": {
            "blocked_payloads": blocked_payloads,
            "allowed_payloads": allowed_payloads,
        },
        "bypass_difficulty": bypass_difficulty,
        "detected_wafs": detected_wafs,
    }


# ============================================================
# 主函数
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        description="WAF 指纹识别工具 - 通过发送恶意 payload 识别 WAF 类型"
    )
    parser.add_argument("--url", required=True, help="目标 URL")
    parser.add_argument("--timeout", type=int, default=10, help="请求超时秒数（默认 10）")
    parser.add_argument("--output", "-o", help="结果保存文件路径（可选）")
    args = parser.parse_args()

    try:
        result = detect_waf(args.url, args.timeout)

        json_output = json.dumps(result, ensure_ascii=False, indent=2)

        if args.output:
            try:
                with open(args.output, "w", encoding="utf-8") as f:
                    f.write(json_output)
                print(f"结果已保存到: {args.output}")
            except IOError as e:
                print(json.dumps({"error": f"写入文件失败: {e}"}), file=sys.stderr)
                print(json_output)
        else:
            print(json_output)

    except KeyboardInterrupt:
        print(json.dumps({"error": "用户中断"}), file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(json.dumps({"error": f"检测失败: {e}"}), file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
